### ISSUE TITLE
Could not find module `@embroider/macros` imported from `@ember/legacy-built-in-components/index`

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/ember-legacy-built-in-components#10]
In v0.4.0 when importing in an addon. ember/ember-cli 3.28

**Comment by SergeAstapov** [comment]
@Gaurav0 do you have a reproduction? `"@embroider/macros": "^0.47.1"` is listed in `dependencies` of this add-on and [v3.0.1 had the same dependency](https://github.com/emberjs/ember-legacy-built-in-components/blob/v0.3.1/package.json#L37) so does not seem smth introduced in v4.0.0.

Tried minimal reproduction via
 ```sh
ember addon test && cd test && ember install @ember/legacy-built-in-components
// make edits and add imports in tests/dummy/app/controllers/application.js
ember s
```

and things just work

**Comment by Gaurav0** [comment]
Thanks for looking into this @SergeAstapov . Here's my branch: https://github.com/secondstreet/ember-material-components-web/tree/repro_legacy_built_ins. I get the error when running ember test. You can see the error here: https://github.com/secondstreet/ember-material-components-web/runs/4313309166?check_suite_focus=true

For some reason I have an entry for `@embroider/macros/runtime` but not `@embroider/macros` in `requirejs.entries`

**Comment by void-mAlex** [comment]
hello @Gaurav0 is this still happening?
I ran your branch locally and only had one failing test 
> not ok 1 Chrome 117.0 - [272 ms] - Acceptance | demo: visiting /
    ---
        actual: >
            null
        stack: >
            Error: Element not found when calling `click('.toggle-demo-visibility')`.

and no mention of @embroider/macros

**Comment by Gaurav0** [comment]
This turned out to  be a bug in yarn v1 workspaces.
