### ISSUE TITLE
Possibly broken <LinkTo>

### ISSUE THREAD

**Issue by BobrImperator** [emberjs/ember-legacy-built-in-components#12]
While I was working on ember-engines, I found out that LinkTo wouldn't work correctly. When clicked, the transition wouldn't fire.
https://github.com/ember-engines/ember-engines/pull/798/files#diff-a450f3a85dfbf538ccb97a9f73a2e49359d87c3c09e6fe3842adf909f1b74809R42

I think it might be because `_generateTransition` creates a callback which is never called.
https://github.com/emberjs/ember-legacy-built-in-components/blob/main/addon/components/link-to.ts#L810

The link-to implementation in ember 3.28 on the other hand passes the generated callback to `flaggedInstrument` which fires the transition.
https://github.com/emberjs/ember.js/blob/v3.28.8/packages/%40ember/-internals/glimmer/lib/components/-link-to.ts#L767

**Comment by SergeAstapov** [comment]
@BobrImperator could you please provide some more info? minimal production would be even more appreciated

**Comment by BobrImperator** [comment]
Oh, sorry @SergeAstapov! I was sure I closed the page and didn't create the issue 🙈 
Now that I was called out, I edited the description with my findings :D.
