### ISSUE TITLE
Internal import of `context` from commented out export in components/_internals

### ISSUE THREAD

**Issue by nickschot** [emberjs/ember-legacy-built-in-components#18]
Got a warning from Embroider about a missing export.

The target-action-support mixin provided by this addon tries to import context here: https://github.com/emberjs/ember-legacy-built-in-components/blob/main/addon/mixins/_target_action_support.js#L7

but the export is commented out here: https://github.com/emberjs/ember-legacy-built-in-components/blob/main/addon/components/_internals.ts#L64

**Comment by miguelcobain** [comment]
I just found the same warnings myself.

Here, we're importing `context`: https://github.com/emberjs/ember-legacy-built-in-components/blob/main/addon/mixins/_target_action_support.js#L7

But here we never export it: https://github.com/emberjs/ember-legacy-built-in-components/blob/main/addon/components/_internals.ts
(the export is commented)

What's the correct way forward?

**Comment by tcjr** [comment]
I'm seeing this now since upgrading to Ember 4 and updating my code to use this.  I have a component with this import:
```javascript
import { TextArea } from "@ember/legacy-built-in-components";
```
and the build outputs this twice:

```
WARNING in ./node_modules/@ember/legacy-built-in-components/mixins/_target_action_support.js 36:20-34
export 'context' (imported as 'context') was not found in '../components/_internals' (possible exports: HAS_BLOCK, isSimpleClick)
 @ ./node_modules/@ember/legacy-built-in-components/mixins/text-support.js 4:0-59 113:28-47
 @ ./node_modules/@ember/legacy-built-in-components/components/text-field.js 11:0-54 51:35-51
 @ ./node_modules/@ember/legacy-built-in-components/index.js 39:18-52

```

**Comment by derrabauke** [comment]
:heavy_plus_sign:
