### ISSUE TITLE
Import path does not work in v0.3.1?

### ISSUE THREAD

**Issue by SergeAstapov** [emberjs/ember-legacy-built-in-components#5]
With recent changes in Ember beta, looks like those imports from `README.md` don't work any more:

```js
import {
  Checkbox,
  LinkComponent,
  TextArea,
  TextField
} from '@ember/legacy-built-in-components';
```

[The test app itself uses](https://github.com/emberjs/ember-legacy-built-in-components/blob/v0.3.1/tests/dummy/app/components/legacy-checkbox.js) imports like
```js
export { default } from '@ember/legacy-built-in-components/components/checkbox';
```

The problem comes from the `addon/index.js` file having this snippet:
```js
export const Checkbox = macroCondition(
  dependencySatisfies('ember-source', '>= 3.27.0-beta.1')
)
  ? Ember._LegacyCheckbox.extend()
  : Ember.Checkbox;
```

Unless I'm missing something, `Ember._Legacy*` have been removed in https://github.com/emberjs/ember.js/commit/5d24ae7480aae886d7a526d15332f53fe5b1689c, specifically those lines

```js
// Expose a non-deprecated version for tests and the @ember/legacy-built-in-components addon
Ember[`_Legacy${name}`] = value;
```

@mixonic @chancancode what do you think would be the right fix here? I'm thinking of two options:

1. replace `README.md` import example to (breaking change to addon contract)
```js
export Checkbox from '@ember/legacy-built-in-components/components/checkbox';
```
2. Fix code in `addon/index.js` to be smth like:
```js
macroCondition(dependencySatisfies('ember-source', '>= 3.27.0-beta.1'))
  ? macroCondition(dependencySatisfies('ember-source', '< v4.0.0-beta.9'))
    ? Ember._LegacyCheckbox.extend()
    : importSync('@ember/legacy-built-in-components/components/checkbox')
  : Ember.Checkbox;
```

**Comment by mixonic** [comment]
Released in [v0.4.0](https://github.com/emberjs/ember-legacy-built-in-components/releases/tag/v0.4.0)
